import Container from '@/components/Container/Container';
import Footer from '@/components/Footer/Footer';
import HomeHeroSection from '@/components/HomeHeroSection/HomeHeroSection';
import HomeOptInSection from '@/components/HomeOptInSection/HomeOptInSection';
import LatestRecipesSection from '@/components/LatestRecipesSection/LatestRecipesSection';
import Navigation from '@/components/Navigation/Navigation';
import PopularCategorySection from '@/components/PopularCategorySection/PopularCategorySection';
import SuperDeliciousSection from '@/components/SuperDeliciousSection/SuperDeliciousSection';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <header>
        <Navigation />
      </header>
      <main className={''}>
        <HomeHeroSection />
        <PopularCategorySection />
        <SuperDeliciousSection />
        <LatestRecipesSection />
        <HomeOptInSection />
        <Footer />
      </main>
    </>
  );
}
