import Container from '@/components/Container/Container';
import HomeHeroSection from '@/components/HomeHeroSection/HomeHeroSection';
import Navigation from '@/components/Navigation/Navigation';
import PopularCategorySection from '@/components/PopularCategorySection/PopularCategorySection';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <header>
        <Navigation />
      </header>
      <main className={''}>
        <Container>
          <HomeHeroSection />
          <PopularCategorySection />
        </Container>
      </main>
    </>
  );
}
